config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products do
    member do
      post 'add_to_cart'
    end
  end

  get 'cart' => 'products#show_cart', as: :show_cart
  delete 'clear_cart' => 'products#clear_cart', as: :clear_cart
  resources :orders, only: [:create]

  root 'products#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base

  acts_as_list

  has_many :product_categories
  has_many :products, through: :product_categories

  scope :sorted, -> { order(:position) }

  before_create :set_position

  def set_position
    self.position = Category.maximum(:position) + 1
  end

end

app/models/item_set.rb
class ItemSet < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :item_sets, dependent: :destroy
  belongs_to :user


end

app/models/product.rb
class Product < ActiveRecord::Base

  self.per_page = 2

  has_many :product_categories, :dependent => :destroy
  has_many :categories, through: :product_categories
  has_many :item_sets

  before_destroy :ensure_not_references_by_any_set_of_item
  validates :name, :description, :price, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  validates_presence_of :categories


  mount_uploader :image, ImageUploader


  def display_price(currency = nil)
    '$' + self.price.to_s if currency.nil?
  end

  private

  def ensure_not_references_by_any_set_of_item
    if item_sets.empty?
      return true
    else
      errors.add(:base, 'Set of items present')
      return false
    end
  end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base

  belongs_to :product
  belongs_to :category


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :cart_total


  def after_sign_in_path_for(resource)
    sign_in_url = url_for(:action => 'new', :controller => 'sessions', :only_path => false, :protocol => 'http')
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end


  def cart_total
    @cart_total = 0
    if cookies[:cart].present?
      product_ids = cookies[:cart].split(',')
      product_ids.each do |product_id|
        product = Product.find(product_id)
        @cart_total += product.price
      end
    end
    @cart_total
  end

end

app/controllers/item_sets_controller.rb
class ItemSetsController < ApplicationController

  def create
    product = Product.find(params[:product_id])
    @item_set = @order.item_sets.build(product: product)

    respond_to do |format|
      if @item_set.save
        format.html {redirect_to @item_set.order}
        format.json {render action:'show', status: :created, location: @item_set}
      else
        format.html { render action: 'new'}
        format.json {render json: @item_sets.errors, status: :unprocessable_entity}
      end
    end
  end


private
  def item_sets_params
    params.require(:item_set).permit(:product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :check_auth, only: [:create]

  def create
    products = []
    if cookies[:cart].present?
      product_ids = cookies[:cart].split(',')
      uniq_product_ids = product_ids.uniq
      uniq_product_ids.each do |product_id|
        product = Product.find(product_id)
        quantity = product_ids.count(product_id)
        products << [product, quantity]
      end
    end

    order = Order.new
    order.user = current_user
    order.total_cost = @cart_total
    order.save!
    products.each do |product, quantity|
      item_set = ItemSet.new
      item_set.order = order
      item_set.product = product
      item_set.quantity = quantity
      item_set.price = product.price
      item_set.save
    end

    OrderMailer.delay.order_confirmation(order)

    cookies[:cart] = nil

    flash[:notice] = "Success. You will receive confirmation mail soon."

    redirect_to root_path

  end


  private

  def check_auth
    unless current_user
      flash[:notice] = "Sorry, please login first."
      redirect_to new_user_session_path
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.paginate(:page => params[:page])
  end

  def show

  end

  def show_cart
    @products = []
    if cookies[:cart].present?
      product_ids = cookies[:cart].split(',')
      uniq_product_ids = product_ids.uniq
      uniq_product_ids.each do |product_id|
        product = Product.find(product_id)
        quantity = product_ids.count(product_id)
        @products << [product, quantity]
      end
    end

  end

  def add_to_cart

    product_id = params[:id]

    if cookies[:cart].present?
      products = cookies[:cart].split(',')
      products << product_id
      cookies[:cart] = products.join(',')
    else
      cookies[:cart] = product_id
    end

    redirect_to :back

  end

  def clear_cart

    cookies[:cart] = nil

    redirect_to root_path

  end

  def remove_from_cart

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
  <meta name="viewport" content="width=device-width" />
  <title>BestShop</title>

  <!-- Font CSS Link -->
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <!-- Font CSS Link -->


  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container main">
    <div class="row">
      <div class="header_top">
        <div class="currency_translator span5">
          <div class="currency">
            CURRENCY:
            <select class="select_bg">
              <option value="dollar">DOLLAR</option>
              <option value="euro">EURO</option>
              <option value="taka">TAKA</option>
              <option value="rupe">RUPE</option>
            </select>
          </div>
          <ul class="translator">
            <li class="en"><a class="active" href="#">EN</a></li>
            <li class="en"><a href="#">ES</a></li>
            <li class="en"><a href="#">FR</a></li>
          </ul>
        </div>
        <div class="account_login span7">

          <ul class="account_info">
            <li><a href="#"><img alt="" src="/assets/my_account.png"> MY ACCOUNT</a></li>
            <li><a href="#"><img alt="" src="/assets/mywish_list.png"> MY WISHLIST</a></li>
            <li><a href="<%= show_cart_path %>"><img alt="" src="/assets/shopping_cart.png"> MY CART</a></li>
            <li><a href="checkout.html"><img alt="" src="/assets/checkout.png"> MY CHECKOUT</a></li>
            <% unless current_user %>
                <li><a href="<%= new_user_session_path %>"><img alt="" src="/assets/log_out.png"> SIGN UP / SIGN IN</a></li>
            <% else %>
                <li><a href="<%= url_for(destroy_user_session_path) %>" data-method="delete"><img alt="" src="/assets/log_out.png"> SIGN OUT</a></li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
    <div class="row">
      <div class="header_top">
        <div class="span4">
          <a href="index-2.html">
            <div class="logo"></div>
          </a>
        </div>
        <div class="call_info span4">
          <p>PHONE: <span class="color">1 (234) 56 78 901</span></p>
          <p>Call us Monday - Saturday: 9:00 am - 6:00 pm</p>
        </div>
        <div class="cart_info span3">
          <div class="cart_data">Shopping Cart - <%= number_to_currency @cart_total %></div>
          <button class="cart_btn btn btn-navbar"><img alt="" src="/assets/shopping_cart_btn_img.png"></button>
          <!--div class="item_cart_content">
            <div class="item_cart_wrap collapse">
              <div class="item_cart">
                <p class="item_cart_products">No Products</p>
                <p class="item_cart_info">Shipping - $0.00</p>
                <p class="item_cart_info">Total - $0.00</p>
                <button class="checkout">Checkout</button>
                <button class="cart">Cart</button>
              </div>
            </div>
          </div-->
        </div>
      </div>
    </div>

  </div>
</div>
<div class="navigation navbar">

  <div class="row">
    <div class="navbar">
      <div class="container main">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- Be sure to leave the brand out there if you want it shown -->

        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <!-- .nav, .navbar-search, .navbar-form, etc -->
          <ul class="sf-menu">
            <li><a href="index-2.html">Home</a></li>
            <li class="deeper parent current">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Men
              </a>
              <ul class="dropdown-menu">
                <li><a href="men.html">Dresses</a></li>
                <li><a href="product_details_men.html">Product Details</a></li>
              </ul>
            </li>
            <li class="deeper parent dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Women
              </a>
              <ul class="dropdown-menu">
                <li><a href="grid.html">Dresses</a></li>
                <li><a href="bag.html">Bags</a></li>
                <li><a href="beautiful.html" >Beauty</a></li>
                <li><a href="bikini.html">Bikini</a></li>
                <li><a href="nightwear.html">Nightwear</a></li>
                <li><a href="club.html" >Club</a></li>
                <li><a href="doll.html">Doll</a></li>
                <li><a href="product_details_women.html">Product Details</a></li>
              </ul>
            </li>
            <li>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Kids
              </a>
              <ul class="dropdown-menu">
                <li><a href="kid.html">Dresses</a></li>
                <li><a href="product_details_kid.html">Product Details</a></li>
              </ul>
            </li>
            <li><a href="#">Blogs</a>
              <ul class="dropdown-menu">
                <li><a href="blog.html">Blog View</a></li>
                <li><a href="single.html">Single View</a></li>
              </ul>
            </li>
            <li><a href="contact.html">Contact Us</a></li>
            <li><a href="#">Styles</a>
              <ul class="dropdown-menu">
                <li><a href="index-2.html">Red</a></li>
                <li><a href="http://demo.webpentagon.com/themeforest/html/bestshop_green/index.html">Green</a></li>
                <li><a href="http://demo.webpentagon.com/themeforest/html/bestshop_orange/index.html">Orenge</a></li>
                <li><a href="http://demo.webpentagon.com/themeforest/html/bestshop_purple/index.html">Purple</a></li>
                <li><a href="http://demo.webpentagon.com/themeforest/html/bestshop_brown/index.html">Brown</a></li>
              </ul>
            </li>
          </ul>
          <div class="search">
            <input type="search" name="search" placeholder="search">
            <button class="search_btn">
              <img alt="" src="/assets/icon_search.png">
            </button>
          </div>

        </div>

      </div>
    </div>

  </div>

</div>

<div class="breadcrumbs">
  <div class="container main">
    <ul>
      <li><a href="#">Home</a></li><li>&#47;</li><li class="active"><a href="#">Men</a></li>
    </ul>
  </div>
</div>

<div class="main_content">
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>


</div>

<div class="contact_info">
  <div class="container main">
    <ul class="row">
      <li class="follow-us span4">
        <div class="follow-social">Follow us on:</div>
        <div class="social-icon">
          <ul>
            <li class="fb">
              <a href="#"><img alt="" src="/assets/social/facebook.png"></a>
            </li>
            <li class="tw">
              <a href="#"><img alt="" src="/assets/social/twitter.png"></a>
            </li>
            <li class="rss">
              <a href="#"><img alt="" src="/assets/social/rss.png"></a>
            </li>
            <li class="yt">
              <a href="#"><img alt="" src="/assets/social/youtube.png"></a>
            </li>
          </ul>
        </div>
      </li>
      <li class="span4">
        <div class="free-shipping">
          <div class="free-shipping-wrap">
            <div class="free-shipping-image">
              <img alt="" src="/assets/social/shiping-truck.png">
            </div>
            <div class="free-shipping-info">
              <div id="free-shipping-info-title">
                Free Shipping
              </div>
              <div id="free-shipping-info">
                On Orders  Over $ 499
              </div>
            </div>
          </div>
        </div>
      </li>
      <li class="contact-no span4">
        <div class="contact-no-wrap">
          <div class="contact-no-image">
            <img alt="" src="/assets/social/telephone.png">
          </div>
          <div class="contact-no-info">
            <div id="contact-no-info-title">
              Order Online
            </div>
            <br/>
            <div id="contact-no-info">
              <p>Phone:</p>
              <p id="nb">1 (234) 56 78 901</p>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>

</div>

<div class="footer">
  <div class="footer-top">
    <div class="container main" id="footer-top">

      <div class="row">
        <div class="span3 footer-col">
          <div class="widget-info">
            <div class="widget-title">Information</div>
            <div class="line"></div>
            <div class="widget-content">
              <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Customer Service</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Site Map</a></li>
                <li><a href="#">Contact Us</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="span3 footer-col">
          <div class="widget-info">
            <div class="widget-title">Why Buy From Us</div>
            <div class="line"></div>
            <div class="widget-content">
              <ul>
                <li><a href="#">Shipping & Returns</a></li>
                <li><a href="#">Secure Shopping</a></li>
                <li><a href="#">International Shipping</a></li>
                <li><a href="#">Affiliates</a></li>
                <li><a href="#">Group Sales</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="span3 footer-col">
          <div class="widget-info">
            <div class="widget-title">My Account</div>
            <div class="line"></div>
            <div class="widget-content">
              <ul>
                <li><a href="#">Sign In</a></li>
                <li><a href="#">Customer Service</a></li>
                <li><a href="#">My Wishlist</a></li>
                <li><a href="#">Track My Order</a></li>
                <li><a href="#">Help</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="span3 footer-col">
          <div class="widget-info">
            <div class="widget-title">Newsletter</div>
            <div class="line"></div>
            <div class="widget-content">
              <input type="text" name="mail" placeholder="Your E-mail Address">
              <button class="go_btn">Go</button>
              <br/>
              <p>Store Location: <span>8601 Creat Labaratory, New York, D05 86GR</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container main" id="footer-bottom">
      <div class="row">
        <div class="span8 footer-col">
          Copyright &#169; 2013 <a href="#">Fedimo</a>. All rights reserved.
        </div>
        <div class="span4 footer-col">
          <ul>
            <li><a href="#"><img alt="" src="/assets/payment-getway/1.png"></a></li>
            <li><a href="#"><img alt="" src="/assets/payment-getway/2.png"></a></li>
            <li><a href="#"><img alt="" src="/assets/payment-getway/3.png"></a></li>
            <li><a href="#"><img alt="" src="/assets/payment-getway/4.png"></a></li>
            <li><a href="#"><img alt="" src="/assets/payment-getway/5.png"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>


</body>
</html>

app/views/orders/create.html.erb
Success

app/views/products/_cart_item.html.erb
<div class="cart_area_list">
  <div class="cart_area_content">
    <div class="row" id="<%= product.id %>">
      <div class="span3 cart_remove">
        <p><input type="checkbox" value="product1" name="product1" disabled="disabled" title="Under development"></p>
      </div>
      <div class="span2 cart_image">
        <%= image_tag product.image_url(:small) %>
      </div>
      <div class="span2 cart_product_name">
        <p><%= product.name %></p>
      </div>
      <div class="span2 cart_quantity">
        <p>
          <%= quantity %>
          <!--select class="qnt">
            <option value="1">0</option>
            <option value="2">1</option>
            <option value="3">2</option>
            <option value="4">3</option>
            <option value="5">4</option>
            <option value="6">5</option>
            <option value="7">6</option>
            <option value="8">7</option>
            <option value="9">8</option>
            <option value="10">9</option>
          </select-->
        </p>
      </div>
      <div class="span3 cart_total_price">
        <p><%= number_to_currency product.price*quantity %></p>
      </div>
    </div>
  </div>
</div>

app/views/products/_item.html.erb
<li class="mix" data-name="Acadia" data-area="47452.80">
  <div class="meta name">
    <div class="img_wrapper loaded">
      <img alt src="<%= product.image_url(:thumb) %>" onload="imgLoaded(this)">
    </div>

  </div>

  <div class="product_info new-product-info">
    <div>
      <div class="new-product-price"><%= number_to_currency product.price %></div>
      <div class="new-product-bg">
        <div class="newE-product-cart_like">
          <div class="new-product-cart_like">
            <div class="new-product-cart"><%= link_to(image_tag('new-product/shoping-info/cart-image.png'), add_to_cart_product_path(product), method: :post) %></div>
            <div class="new-product-like"><%= link_to(image_tag('new-product/shoping-info/like-img.png')) %></div>
          </div>
        </div>
        <div class="new-product-details"><a href="#">Details</a></div>
      </div>
    </div>
  </div>
  <div class="product_description product_info">
    <div class="title"><%= product.name %></div>
    <div class="content"><%= product.description %></div>
  </div>
  <div class="meta product_description">
    <div class="title"><%= product.name %></div>
    <div class="content"><%= product.description %></div>
  </div>
  <div class="meta product_description">
    <div class="popular-product-info">
      <div>
        <div class="popular-product-price"><%= number_to_currency product.price %></div>
        <div class="popular-product-bg">
          <div class="popular-product-cart_like">
            <div class="popular-product-cart_like">
              <div class="popular-product-cart"><%= link_to(image_tag('new-product/shoping-info/cart-image.png'), add_to_cart_product_path(product), method: :post) %></div>
              <div class="popular-product-like"><%= link_to(image_tag('new-product/shoping-info/like-img.png')) %></div>
            </div>
          </div>
          <div class="popular-product-details"><a href="#">Details</a></div>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/products/index.html.erb
  <div class="container main product_style">
    <div class="row">
      <div class="span9 product-area">

        <!--div class="discount_banner">
          <img alt="" src="/assets/discount_banner.png">
        </div-->

        <!--Nav section for mixtop-->

        <nav class="controls just view_as top">
          <div class="group span4 left-order Sorts">
            <p>view as:</p>
            <ul>
              <li><div class="button" id="ToGrid"></div></li>
              <li><div class="button" id="ToList"></div></li>
            </ul>
          </div>
          <div class="group span5 right-order sorting" id="Filters">
            <div class="text-show">
              <p>show:</p>
            </div>
            <div class="drop_down sort">
              <div class="select_bg_sort"><p>Position</p></div>
              <ul class="">
                <li class="active" data-filter="all" data-dimension="region">All</li>
                <li data-filter="alaska" data-dimension="region">New</li>
                <li data-filter="intermountain" data-dimension="region">Intermountain</li>
                <li data-filter="northeast" data-dimension="region">Fashion</li>
                <li data-filter="pacific_west" data-dimension="region">Smart</li>
                <li data-filter="southeast" data-dimension="region">Beautiful</li>
              </ul>
            </div>
            <div class="text-show">
              <p>show:</p>
            </div>
            <div class="drop_down show">
              <div class="select_bg_pn"><p>1</p></div>
              <ul class="">
                <li class="active" data-filter="all" data-dimension="recreation">1</li>
                <li data-filter="camping" data-dimension="recreation">2</li>
                <li data-filter="climbing" data-dimension="recreation">3</li>
                <li data-filter="fishing" data-dimension="recreation">4</li>
                <li data-filter="swimming" data-dimension="recreation">5</li>
              </ul>
            </div>
          </div>
        </nav>

        <!--Nav section for mixtop-->

        <ul id="Parks" class="just list">

          <% @products.each do |product| %>
              <%= render partial: 'item', locals: {product: product}%>
          <% end %>

        </ul>

        <!--Nav section for mixtop-->

        <nav class="controls just view_as bottom">
          <div class="group span5 left-order Sorts">
            <p>view as:</p>
            <ul>
              <li><div class="button" id="ToGrid1"></div></li>
              <li><div class="button" id="ToList1"></div></li>
            </ul>
          </div>
          <div class="group span4 right-order">
            <!-- Start pagination -->
            <div class="pagination">
              <%= will_paginate(@products, :class => '', :previous_label => '<', :next_label => '', :renderer => PaginationListLinkRenderer) %>
              <!--ul>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li class="active"><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#"></a></li>
              </ul-->
            </div>
            <!-- End pagination -->
          </div>
        </nav>

        <!--Nav section for mixtop-->
      </div>
      <div class="span3 widget-area">
        <div class="right-sidebar">
          <div class="widget-info">
            <div class="widget-title">Categories</div>
            <div class="line"></div>
            <div class="widget-content">
              <ul>
                <li><a href="#">Dresses</a></li>
                <li><a href="#">Bags & Purses</a></li>
                <li><a href="#">Coats & Jackets</a></li>
                <li><a href="#">Accessories</a></li>
                <li><a href="#">Designer</a></li>
                <li><a href="#">Jeans</a></li>
                <li><a href="#">Jewellery & Watches</a></li>
              </ul>
            </div>
          </div>
          <div class="widget-info">
            <div class="widget-title">By Price</div>
            <div class="line"></div>
            <div class="widget-price">
              <ul>
                <li><a href="#">0 - $1,700.00</a></li>
                <li><a href="#">$20 - $2,800.00</a></li>
                <li><a href="#">$50 - $2,900.00</a></li>
                <li><a href="#">$75 - $3,990.00</a></li>
                <li><a href="#">$100 - $4,600.00</a></li>
              </ul>
            </div>
          </div>
          <div class="widget-info">
            <div class="widget-title">Color</div>
            <div class="line"></div>
            <div class="widget-price">
              <select class="select_color">
                <option value="red">Red</option>
                <option value="blue">Blue</option>
                <option value="green">Green</option>
                <option value="yellow">yellow</option>
              </select>
            </div>
          </div>
          <div class="widget-info">
            <div class="widget-title">Manufacturer</div>
            <div class="line"></div>
            <div class="widget-content">
              <form>
                <div><input type="checkbox" name="vehicle" value="Bike"><div class="brand_name">Adidas</div></div>
                <div><input type="checkbox" name="vehicle" value="Car"><div class="brand_name">Nike</div></div>
                <div><input type="checkbox" name="vehicle" value="Bike"><div class="brand_name">T-Shirt</div></div>
                <div><input type="checkbox" name="vehicle" value="Car"><div class="brand_name">Puma</div></div>
                <div><input type="checkbox" name="vehicle" value="Bike"><div class="brand_name">Denim</div></div>
                <div><input type="checkbox" name="vehicle" value="Car"><div class="brand_name">Dedeman</div></div>
                <div><input type="checkbox" name="vehicle" value="Car"><div class="brand_name">New wear</div></div>
              </form>
            </div>
          </div>
          <div class="widget-info">
            <div class="widget-title">View History</div>
            <div class="line"></div>
            <div class="widget-content">
              <div class="history-product-image">
                <%= link_to(image_tag('product-list/htstory.png')) %>
              </div>
              <div id="feature-post-content">
                <div>
                  <button class="shop-now">Shop Now</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      </div>

app/views/products/show_cart.html.erb
<div class="container main">
  <div class="checkout_area">
    <h2 class="title-wrap">
      Shopping Cart
    </h2>
    <div class="line"></div>

    <div class="cart_area">

      <div class="cart_area_heading">
        <div class="row">
          <div class="span3 cart_remove">
            <p>Remove</p>
          </div>
          <div class="span2 cart_image">
            <p>Image</p>
          </div>
          <div class="span2 cart_product_name">
            <p>Product Name</p>
          </div>
          <div class="span2 cart_quantity">
            <p>Quantity</p>
          </div>
          <div class="span3 cart_total_price">
            <p>Total Price</p>
          </div>
        </div>
      </div>

      <% @products.each do |product, quantity| %>
        <%= render partial: 'cart_item', locals: {product: product, quantity: quantity} %>
      <% end %>

    </div>
  </div>

  <div class="row total_cost">
    <div class="span6 gap_section">

    </div>
    <div class="span6 total_cost_section">
      <div class="total_cart_cost">
        <div class="cart_level">
          <p><span>total:</span></p>
        </div>
        <div class="cart_amount">
          <p><span><%= number_to_currency @cart_total %></span></p>
        </div>
      </div>
      <div class="total_cart_cost_btn">
        <a href="<%= clear_cart_path %>" data-method="delete"><button class="checkout">clear cart</button></a>
        <a href="<%= orders_path %>" data-method="post"><button class="continue">order</button></a>
      </div>
    </div>
  </div>
</div>